### ISSUE TITLE
Definable @param format

### ISSUE THREAD

**Issue by GeekyEggo** [wiggin77/codedox#1]
I was wondering if it's currently possible to define the `@param` format?

Within [Commenter.hx#L186](https://github.com/wiggin77/codedox/blob/master/src/wiggin/codedox/Commenter.hx#L186) the construction of param comments could provide the current item's information as parameters; these could then be used in conjunction with a user-definable `@param` format, e.g.

    {
        "codedox": {
            "paramformat": "@param {{${type}}} ${name}"
        }
       ...
    }

Then for a given parameter `name: string`, the result would be `@param {string} name`

**Comment by wiggin77** [comment]
Good idea.  I'll add this soon.

**Comment by wiggin77** [comment]
As of 1.2.1 you can customize @params and @return.  To add types to @params:
```
{
    "codedox": {
        "paramFormat": "@param {${type}} ${name}"
    }
   ...
}
```
