### ISSUE TITLE
"commentend" has a hardcoded space?

### ISSUE THREAD

**Issue by Gama11** [wiggin77/codedox#10]
I'm trying to configure codedox to generate comments with the style with which they're commently used in the Haxe standard library (and also vshaxe).

They look like this:

```haxe
/**
	Description
**/
```

To achieve this, I added this setting: `"commentend": "**/"`

However, it looks like there's no way to avoid an extra space in front of `**/` from being generated:

![](http://i.imgur.com/OtWQDam.gif)

**Comment by wiggin77** [comment]
Thanks.  This is fixed via 616f9e6d91462b693c857f143cad8dec03e173ce. 

If you don't want to wait for a marketplace release (probably next week) you can `haxe build-release.hxml` from master and copy `out/codedox.js` to your extensions directory `.../.vsode/extensions/wiggin77.codedox-1.2.3/out/codedox.js`.  Or just clone the repo there.

**Comment by wiggin77** [comment]
... also these settings should give you what you want:
```json
"codedox": {
    "commentbegin": "/**",
    "commentprefix": "      ",
    "commentend": "**/",
}
```

**Comment by Gama11** [comment]
Thanks! 👍
