### ISSUE TITLE
Spaces added for non-function docs

### ISSUE THREAD

**Issue by Gama11** [wiggin77/codedox#12]
The use case described in #10 now works well for functions. 👍 

However, it looks like there's still an issue with docs elsewhere (for instance type or variable declarations). These are not "auto-expanded" to multiple lines like function docs, which is ok - however, it seems two spaces are inserted for these, which means when pressing enter, you have an additional space in front of the  `**/` again.

![](http://i.imgur.com/zoqrvu6.gif)

I played around with a few of the settings (`autoInsert` etc) but they didn't seem to make a difference.

Here are the settings the gif was recorded with:

```haxe
"codedox": {
    "commentbegin": "/**",
    "commentprefix": "    ",
    "commentend": "**/",
    "headerbegin": "/**",
    "headerprefix": "    ",
    "headerend": "**/"
}
```

Btw, it looks like the "header" settings are used for type and variable declarations (not a problem per se, but might be confusing to some).

**Comment by wiggin77** [comment]
This was a problem with the `onEnterRules`.  Those rules are dynamically built now based on the config.  I tested with your settings and all looks good.  Also, there is a new config prop `alwaysMultiline` which is a bool that determines whether comments for types (e.g. class, typedef, var, etc) default to single or multi-line.  Personally I like single lines for vars and my preferences have accidentally snuck into the defaults.

Grab from `master` branch if you don't want to wait for market release (next week hopefully).

As always, thanks for the feedback and issues.

**Comment by Gama11** [comment]
Awesome work! 👍
