### ISSUE TITLE
Extension needs to run once before picking up key commands

### ISSUE THREAD

**Issue by Stumblor** [wiggin77/codedox#14]
I find that i first need to run

Ctrl-Alt-P > Codedox: Insert comment at cursor

Before any key combinations are observed in the extension. Having run this once, key commands are then picked up successfully, even for newly opened files. Am I missing something?

**Comment by wiggin77** [comment]
I have not seen this.  The extension is supposed to be activated run as soon as a haxe file is loaded - anything the sets the language mode to "Haxe" as seen in the status bar.  

Do you have [vshaxe](https://marketplace.visualstudio.com/items?itemName=nadako.vshaxe) installed?

Do you see "Haxe" as your language mode in the status bar?  
![lang-mode](https://cloud.githubusercontent.com/assets/5024605/22702164/c7573ddc-ed2d-11e6-9d65-434237bc4a07.png)

**Comment by Stumblor** [comment]
That would be why! 

I've been working on a fork to get the extension working with js and vue files. I'll have a look at the activation routine based on your comments.

**Comment by Stumblor** [comment]
That would be why! 

I've been working on a fork to get the extension working with js and vue files. I'll have a look at the activation routine based on your comments.

**Comment by wiggin77** [comment]
Ok, I just saw your PR.  Awesome work!  Is this issue about getting key commands for JS/vue files?  If so, it needs a change to package.json ...  activationEvents needs on onLanguage for javascript and html.

**Comment by Stumblor** [comment]
Great, glad you think so! After adding those items to package.json it all works as expected. Thanks for the help. 👍
