### ISSUE TITLE
No selection with \n in commentdescription

### ISSUE THREAD

**Issue by Gama11** [wiggin77/codedox#16]
I wanted to see if I could use the `"commentdescription"` setting to add an empty line between the description and the following `@param` / `@return`. This works fine - however, with this config, `[Description]` does not get selected anymore:

```json
"codedox": {
    "commentdescription": "[Description]\n"
}
```

![](http://i.imgur.com/2a5xVPh.gif)

Also, `"commentprefix"` is not included here - it probably should be?

**Comment by wiggin77** [comment]
Newlines are now supported for `commentdescription`, `paramFormat`, and `returnFormat`.

**Comment by Gama11** [comment]
Works great now as far as I can tell, thanks!

**Comment by Gama11** [comment]
Btw, I've been wondering if you'd be interested in joining the vshaxe organization (codedox still remaining as its own separate extension). :)

It seems like codedox would be a good fit for the collection of repos / extensions that vshaxe has - and hopefully it would give the codedox repo some more visibility.

If you're not interested, that's absolutely fine too! For instance, you might have (valid) concerns about putting yourself too much into the "Haxe corner" (I think I've seen you mention plans about eventually supporting other languages too).

**Comment by wiggin77** [comment]
Adding codedox to the vshaxe org sounds like a good idea.  I would like to start helping you and Dan out with those projects anyway.

I do plan to add more languages since there is interest, but the primary focus of codedox is Haxe, since that is my focus.  I might use the codebase to build a generic ext for the marketplace for the other languages -- or just keep the Haxe branding and add some keywords. Not sure yet.

**Comment by Gama11** [comment]
Great! 👍 

I don't actually have invite powers myself, @nadako or @simn will send you one. :)

As for transferring repos, there's a "Transfer repo" option down in the repo settings (in the "Danger Zone"). I think you need admin rights in vshaxe to be able to make the transfer.

**Comment by Simn** [comment]
Invite sent!

**Comment by Gama11** [comment]
@wiggin77 You should have received a Slack invite too. :)
