### ISSUE TITLE
Haxe comment conventions for dox

### ISSUE THREAD

**Issue by jasonsturges** [wiggin77/codedox#20]
Shouldn't this extension adhere to Haxe dox-style comment conventions?  

By default, it implements a JSDoc / ASDoc style comments:

![dox](https://cloud.githubusercontent.com/assets/1213591/24583842/d53f7710-171d-11e7-9a41-7a3f73b0c367.gif)

When this style of comment is run through dox, the resulting documentation does not parse method parameters correctly:

```
    /**
     *  Constructor
     *  @param delay - The delay in ms to make the call.
     *  @param scope - An object that specifies the scope (value of `this` object) within the function body.
     *  @param callback - Function to call after the specified delay.
     *  @param params - Parameters to be passed to the function.
     */
    public function new(delay:Int = 1, ?scope:Dynamic, ?callback:Dynamic, ?params:Array<Dynamic>) {
```

![image](https://cloud.githubusercontent.com/assets/1213591/24583864/9ad90180-171e-11e7-883a-cde4564176d0.png)

Instead, a configuration must be added:

```
    "codedox": {
        "commentbegin": "/**",
        "commentprefix": "    ",
        "commentend": "**/",
```

These conventions are correctly interpreted to produce dox documentation

```
    /**
        Constructor
        @param delay     The delay in ms to make the call.
        @param scope     An object that specifies the scope (value of `this` object) within the function body.
        @param callback  Function to call after the specified delay.
        @param params    Parameters to be passed to the function.
    **/
    public function new(delay:Int = 1, ?scope:Dynamic, ?callback:Dynamic, ?params:Array<Dynamic>) {
```
![image](https://cloud.githubusercontent.com/assets/1213591/24583888/43786e70-171f-11e7-8d82-a7a2816670c0.png)

Why are these conventions not implemented by default?

**Comment by wiggin77** [comment]
Thanks for your feedback.  Codedox actually started as a documentation tool intended for multiple languages and the "dox" part of the name unintentionally collided with the "dox" tool.  However my focus turned to Haxe and now the tool is exclusively maintained for Haxe and I agree it I should get it working with Dox.  

The defaults are based on reviewing as much Haxe code as I could find on github, including all the big libraries and frameworks.  The majority of code I found uses JSDoc style comments, whereas the bulk of code using "haxe"-style is std and libraries made by the core Haxe developers.  Based on that, I think I would rather invest time in making Dox work with JSDoc comments so the majority of projects can use it.  I captured some stats a while back that I will try to dig up. 

Happy to hear any different opinions on that.  It's just where I landed on it.

**Comment by wiggin77** [comment]
...also I guess I could add to the setup "wizard" something that sets JSDoc or Haxe-style defaults.

**Comment by jasonsturges** [comment]
That makes sense.

Agreed, in that I would prefer Dox to use standard conventions of JSDoc instead of the awkward `/**` and `**/` conventions.

In the statistical analysis, I wonder how many Haxe projects actually use dox for documentation, as many are likely just commenting code using known or IDE built-in conventions.  In libraries I've observed, majority do use JSDoc-style conventions.

I'll leave this in favor of updating Dox to be comment-agnostic.  Thanks.

**Comment by wiggin77** [comment]
Update:  it looks like Dox handles JSDoc/JavaDoc syntax fine.  It appears to be the hyphen between param name and description that is tripping it up.  I will change the default for that as the hyphen is less commonly used.  I will also look at patching Dox to handle the hyphen.
