### ISSUE TITLE
Is it possible to use this for other syntaxes?

### ISSUE THREAD

**Issue by mrmartineau** [wiggin77/codedox#21]
I use JSDOC style comments in my CSS and Sass and would really like some of the features from this package to be available in those syntaxes. Would it be very hard to allow for these other syntaxes? 

P.S. I realise that some of the more complex features might not be available for these new syntaxes.

**Comment by wiggin77** [comment]
Codedox could be modified to enable it for other language ids.  It would not support uato-populating @param or @return tags but the rest should work.  I'll look into making this an option.

**Comment by mrmartineau** [comment]
@wiggin77 I thought as much. Thanks for looking into it. Let me know if I can help

**Comment by wiggin77** [comment]
I've decided to leave this extension Haxe specific.
