### ISSUE TITLE
File name and base file name Parameters

### ISSUE THREAD

**Issue by smartmonkey007** [wiggin77/codedox#23]
Is it possible to add a filename and baseFileName to the existing parameters.

**Comment by wiggin77** [comment]
Shouldn't be a problem.  I get `baseFileName`, but what would you expect in `filename`?  Full filespec?  Something relative to project path?

**Comment by smartmonkey007** [comment]
I was expecting the full path and file name, but the path relative to the workspace folder would be better.

And thanks for looking into it.

**Comment by wiggin77** [comment]
Fixed in [v1.2.6](https://github.com/vshaxe/codedox/releases/tag/v1.2.6)
