### ISSUE TITLE
Support for function expressions

### ISSUE THREAD

**Issue by redeemefy** [wiggin77/codedox#27]
I'm not sure if this a bug or an enhancement. I'm trying to generate some docs on the following function and docs are not generated.

```javascript
lib.read = (dir, file, callback) => {
  fs.readFile(`${path.join(lib.rootDir, dir, file)}.json`, 'utf-8', (err, data) => {
      callback(err, data)
    }
  )
}
```

My guess is that the extension just work with function declaration.

**Comment by wiggin77** [comment]
It's true, the extension does not currently parse that type of expression for generating docs. I'll look into what it would take to support that.

**Comment by redeemefy** [comment]
> It's true, the extension does not currently parse that type of expression for generating docs. I'll look into what it would take to support that.

I guess we can label `enhancement`?

I have never seen the `.hx` extension.
What's this?

**Comment by wiggin77** [comment]
> I have never seen the `.hx` extension.
> What's this?

Haxe source files.  I assumed you were coding in Haxe (https://haxe.org/).  The Codedox extension  was created to help document Haxe source files.  Haxe has a lamba like function syntax as well, but I see now that you are likely using typescript.

**Comment by redeemefy** [comment]
> > I have never seen the `.hx` extension.
> > What's this?
> 
> Haxe source files. I assumed you were coding in Haxe (https://haxe.org/). The Codedox extension was created to help document Haxe source files. Haxe has a lamba like function syntax as well, but I see now that you are likely using typescript.

I was using it with JS. What's interesting is that the extension is written in Haxe and works in vscode.

**Comment by Gama11** [comment]
Well, Haxe can be compiled to JS.

**Comment by redeemefy** [comment]
What are good resources to learn the language?

**Comment by wiggin77** [comment]
Closing as not related to Haxe.
