### ISSUE TITLE
Indent detection

### ISSUE THREAD

**Issue by Gama11** [wiggin77/codedox#3]
Generated doc comments always seem to use tabs for indentation, even if the rest of the file uses spaces:

![](http://i.imgur.com/djUSr32.gif)

**Comment by wiggin77** [comment]
Actually, it obeys the "editor.insertSpaces" setting.  That said, I agree it should use the same indent as the function being documented.  I'll fix that.  Thanks!

**Comment by Gama11** [comment]
Thanks! :)
