### ISSUE TITLE
Debug output visible in releases

### ISSUE THREAD

**Issue by Gama11** [wiggin77/codedox#4]
[This code](https://github.com/wiggin77/codedox/blob/v1.2.1/src/wiggin/codedox/Commenter.hx#L117-L134) is hidden behind `#if debug`, which suggests to me it's not supposed to show up in marketplace releases. However, it looks like marketplace releases are _debug builds_, as `build.hxml` has `-debug` and `package.json` has `haxe build.hxml` as its prebublish command.

**Comment by wiggin77** [comment]
Thanks.  I forgot all about that.
