### ISSUE TITLE
${type} is inserted as-is without type hints

### ISSUE THREAD

**Issue by Gama11** [wiggin77/codedox#8]
Settings:

```json
"codedox": {
    "paramFormat": "@param ${type} - "
}
```

Due to type inference, it's not uncommon to leave out type hints for parameters. However, it looks `${type}` is not replaced at all in that case:

![](http://i.imgur.com/0DcWId9.gif)

It might be preferable to replace it with an empty string in cases like this?

**Comment by wiggin77** [comment]
Thanks for reporting.  `${type}` is now replaced with an empty string.  I may have to revisit this to better handle the common `{${type}}`.  Not sure empty braces is best.
